### ISSUE TITLE
.SCH files will not open in Autodesk Eagle or Fusion 360

### ISSUE THREAD

**Issue by bryn51** [fablabbcn/smartcitizen-analog-sensor-board#1]
If I need to eyeball the schematic then I need a viewer that opens the files.  I am just guessing what to use; but most likely Eagle.

I find that there is no PDF version of the schematic available to view; and that the (.sch) files will not open in Autodesk Eagle (current version)  or Autodesk 360 (current version).

These issues are easily corrected; and should be.

**Comment by oscgonfer** [comment]
The design files are done in Kicad 5, not supporting Autodesk stuff, sorry.

For the schematic, will add it now.

**Comment by oscgonfer** [comment]
https://github.com/fablabbcn/smartcitizen-analog-sensor-board/blob/master/8-channel/exports/smartcitizen-adc-8ch-step.pdf
